#!/bin/bash

#######################################################################
#  This file is automatically generated if it does not already exist.
#######################################################################

#Tech Support script version
TS_VERSION="1.0.1"

# TRUE=0, FALSE=1
TRUE=0
FALSE=1

# Device Serial Number
SN=$(dmidecode -s chassis-serial-number)
if [ ! $? -eq 0 ]; then
    SN=""
elif [[ $SN = *" "* ]]; then
    #SN contains space charachater inside
    SN=""
fi

# DATESTR: The format of log folder and log file
DATESTR=$(date +"%Y%m%d%H%M%S")
LOG_FOLDER_NAME=""
LOG_FILE_NAME=""

# LOG_FOLDER_ROOT: The root folder of log files
LOG_FOLDER_ROOT=""
LOG_FOLDER_PATH=""
LOG_FILE_PATH=""
LOG_FAST=${FALSE}

# BSP_INIT_FLAG: set by function _check_bsp_init
BSP_INIT_FLAG=""

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

# LOG_FILE_ENABLE=1: Log all the platform info to log files (${LOG_FILE_NAME})
# LOG_FILE_ENABLE=0: Print all the platform info in console
LOG_FILE_ENABLE=1

# HEADER_PROMPT=1 :print file name at log file first line
# HEADER_PROMPT=0 :don't print file name at log file first line
HEADER_PROMPT=1

# ls option
# LS_OPTION="-alu"                 : show all file, file permission, list time and sort it by name
# LS_OPTION="-a | cat | sort"      : list one filename per output line and sort it
LS_OPTION="-alu"

# Log Redirection
# LOG_REDIRECT="2> /dev/null"        : remove the error message from console
# LOG_REDIRECT=""                    : show the error message in console
# LOG_REDIRECT="2>&1"                : show the error message in stdout, then stdout may send to console or file in _echo()
LOG_REDIRECT=""

# Err Log Redirection
LOG_ERR_REDIRECT=""

# I2C Bus
I801_BUS=""
ISMT_BUS=""

# Execution Time
start_time=$(date +%s)
end_time=0
elapsed_time=0

# Options
OPT_BYPASS_I2C_COMMAND=${FALSE}

# Default Platform Variables
MODEL_NAME="NA"
MODEL_ID="NA"
DEPH_ID="NA"
HW_REV_ID="NA"
BUILD_REV_ID="NA"

#################################
#  Platform Specific Block
#################################

# PLAT: This script is compatible with the platform.
PLAT=""

S3IP_CONFIG_FILE="${SCRIPTPATH}/../s3ip_config.yml"
BIOS_BOOT_SEL_REG=""
BIOS_BOOT_SEL_REG_MASK=""
IOPORT_ADDRESS=()

# root_bus,
# grandparent address,grandparent channel,
# parent address,parent channel,
# dev,bus (the initialized bus),addr
CPLD_I2C_POSITION=()

# description,ver_reg,build_reg
# ex: "CPU CPLD,0x600,0x6e0"
# ex: "CPLD1,0x702,0x704"
CPLD_DEV_LPC=()

I2C_DEV_INFO=()

# bus
# grandparent address,grandparent channel,
# parent address,parent channel,
# name, channel number, address
I2C_TREE=()

# bus
# grandparent address,grandparent channel,
# parent address,parent channel,
# address
SYS_EEPROM=""

#  "<ko_name>,<module_name>"
DRIVER_ARRAY=(
   "i2c-smbus.ko,i2c_smbus"
)

BMC_SUPPORT=0
BMC_DEV_STAT_SUPPORT_VER=0
BMC_SEL_RAW_DATA_SUPPORT_VER=0

UCD_BRD=""
UVD_SUPPORT_VER=0

ROV_SUPPORT_VER=0
CPLD_INTR_SUPPORT_VER=0
CPLD_ERR_LOG_SUPPORT_VER=0
BEACON_LED_SUPPORT_VER=0
MEM_CORRECTABLE_ERROR_COUNT_SUPPORT_VER=0
#######################################################################

function _echo {
    local str="$@"

    if [ "${LOG_FILE_ENABLE}" == "1" ] && [ -f "${LOG_FILE_PATH}" ]; then
        echo "${str}" >> "${LOG_FILE_PATH}"
    else
        echo "${str}"
    fi
}

function _printf {
    if [ "${LOG_FILE_ENABLE}" == "1" ] && [ -f "${LOG_FILE_PATH}" ]; then
        printf "$@" >> "${LOG_FILE_PATH}"
    else
        printf "$@"
    fi
}

function _banner {
   local banner="$1"

   if [ ! -z "${banner}" ]; then
       _echo ""
       _echo "##############################"
       _echo "#   ${banner}"
       echo  "#   ${banner}..."
       _echo "##############################"
   fi
}

function _plat_ts_version {
    echo ""
}

function _pkg_version {
    _banner "Package Version"
    _echo "Package Version = ${TS_VERSION}"
    _echo "Platform Configuration Version = $(_plat_ts_version)"
}

function _show_ts_version {
    echo "Package Version = ${TS_VERSION}"
    echo "Platform Configuration Version = $(_plat_ts_version)"
}

function _dd_read_byte {
    local reg=$1
    echo "0x"`dd if=/dev/port bs=1 count=1 skip=$((reg)) status=none | xxd -g 1 | cut -d ' ' -f 2`
}

# -----------------------------------------------------------------------------
# Parse YAML block by capturing lines deeper than the header's indentation.
# Args: $1 = Content String (NOT file path), $2 = Block Name
# -----------------------------------------------------------------------------
function _parse_yaml_block {
    local contents="$1"
    local block="$2"
    awk -v target="$block" '
                $0 ~ "^[ \t]*" target ":" {
                    in_block = 1
                    match($0, /[^ \t]/)
                    indent_len = RSTART - 1
                    print $0
                    next
                }

                in_block {
                    if (NF == 0) { print; next }
                    match($0, /[^ \t]/)
                    current_indent = RSTART - 1
                    if (NF == 0) { print; next }
                    if (current_indent > indent_len) {
                        print $0
                    } else {
                        exit
                    }
                }
            '<<< "$contents"
}

# -----------------------------------------------------------------------------
# _get_yaml_attr_value: Retrieves a value from a YAML file using a dot-separated path.
# Logic: Iteratively drills down blocks (e.g., "a.b.c") and extracts the final clean value.
# Usage: _get_yaml_attr_value <attr_path>
# -----------------------------------------------------------------------------
function _get_yaml_attr_value {
    local attrs="$1"
    local attr_array=(${attrs//./ })

    [ ! -f "$S3IP_CONFIG_FILE" ] && return 0
    local contents="$(cat "$S3IP_CONFIG_FILE")"
    for attr in "${attr_array[@]}"; do
        contents=$(_parse_yaml_block "$contents" "$attr")
    done
    echo "$contents" |
        grep -E "^[[:space:]]*${attr}:" |
        sed "s/^[[:space:]]*${attr}:[[:space:]]*//" |
        tr -d '"'
}

function _check_env {
    #_banner "Check Environment"

    # check basic commands
    local cmd_array=("ipmitool" "lsusb" "dmidecode")
    for (( i=0; i<${#cmd_array[@]}; i++ ))
    do
        ret=`which ${cmd_array[$i]}`

        if [ ! $? -eq 0 ]; then
            _echo "${cmd_array[$i]} command not found!!"
            exit 1
        fi
    done

    if [ "${LOG_FILE_ENABLE}" == "1" ]; then
        mkdir -p "${LOG_FOLDER_PATH}"

        if [ ! -d "${LOG_FOLDER_PATH}" ]; then
            _echo "[ERROR] invalid log path: ${LOG_FOLDER_PATH}"
            exit 1
        fi

        if [ "${HEADER_PROMPT}" == "1" ]; then
            echo "${LOG_FILE_NAME}" > "${LOG_FILE_PATH}"
        else
            touch "${LOG_FILE_PATH}"
        fi
    fi

    # get i2c root
    _get_i2c_root
    if [ ! -z ${I801_BUS} ]; then
        _echo "[I801 bus ]: ${I801_BUS}"
    fi

    if [ ! -z ${ISMT_BUS} ]; then
        _echo "[ismt bus ]: ${ISMT_BUS}"
    fi

    # check BSP init
    _check_bsp_init

    # Set platform specific variables
    if declare -F "_set_plat_vars" > /dev/null; then
        _set_plat_vars
    fi
}

function _check_filepath {
    local filepath=$1
    local silent="${2:-0}"

    if [ -z "${filepath}" ]; then
        if [ "$silent" = "0" ]; then
            _echo "ERROR, the input string is empty!!!"
        fi
        return ${FALSE}
    elif [ ! -f "$filepath" ]; then
        if [ "$silent" = "0" ]; then
            _echo "ERROR: No such file: ${filepath}"
        fi
        return ${FALSE}
    else
        #_echo "File Path: ${filepath}"
        return ${TRUE}
    fi
}

function _check_dirpath {
    local dirpath=$1
    if [ -z "${dirpath}" ]; then
        _echo "ERROR, the ipnut string is empty!!!"
        return ${FALSE}
    elif [ ! -d "$dirpath" ]; then
        _echo "ERROR: No such directory: ${dirpath}"
        return ${FALSE}
    else
        return ${TRUE}
    fi
}

function _check_i2c_device {
    local i2c_bus=$1
    local i2c_addr=$2

    if [ -z "${i2c_addr}" ]; then
        _echo "ERROR, the input string is empty!!!"
        return ${FALSE}
    fi

    local value=$(eval "i2cget -y -f ${i2c_bus} ${i2c_addr} ${LOG_ERR_REDIRECT}")
    local ret=$?

    if [ $ret -eq 0 ]; then
        return ${TRUE}
    else
        _echo "ERROR: No such device: Bus:${i2c_bus}, Address: ${i2c_addr}"
        return ${FALSE}
    fi
}

function _check_bsp_init {
    _banner "Check BSP Init"

    # As our bsp init status, we look at S3IP slot model_name.
    if [ -f "/sys_switch/slot/slot1/model_name" ]; then
        BSP_INIT_FLAG=1
    else
        BSP_INIT_FLAG=0
    fi

    _echo "[BSP_INIT_FLAG]: ${BSP_INIT_FLAG}"
}

function _get_i2c_root {
    local i2c_0=""
    local i2c_1=""

    if _check_filepath "/sys/bus/i2c/devices/i2c-0/name" ;then
        i2c_0=`cat /sys/bus/i2c/devices/i2c-0/name`
    fi

    if _check_filepath "/sys/bus/i2c/devices/i2c-1/name" ;then
        i2c_1=`cat /sys/bus/i2c/devices/i2c-1/name`
    fi

    if echo "$i2c_0" | grep -q "I801"; then
        I801_BUS=0
    fi

    if echo "$i2c_1" | grep -q "I801"; then
        I801_BUS=1
    fi

    if echo "$i2c_0" | grep -q "iSMT"; then
        ISMT_BUS=0
    fi

    if echo "$i2c_1" | grep -q "iSMT"; then
        ISMT_BUS=1
    fi
}

function _show_system_info {
    _banner "Show System Info"
    local i=0
    local x86_date=`date`
    local x86_uptime=`uptime`
    local bmc_date=$(eval "ipmitool sel time get ${LOG_REDIRECT}")
    local last_login=`last`

    _echo "[X86 Date Time ]: ${x86_date}"
    _echo "[BMC Date Time ]: ${bmc_date}"
    _echo "[X86 Up Time   ]: ${x86_uptime}"
    _echo "[X86 Last Login]: "
    _echo "${last_login}"
    _echo ""

    local cmd_array=("uname -a" "cat /proc/cmdline" "cat /proc/ioports" \
               "cat /proc/iomem" "cat /proc/meminfo" \
               "cat /proc/sys/kernel/printk" \
               "find /etc -name '*-release' -print -exec cat {} \;")

    for (( i=0; i<${#cmd_array[@]}; i++ ))
    do
        _echo "[Command]: ${cmd_array[$i]}"
        local ret=$(eval "${cmd_array[$i]} ${LOG_REDIRECT}")
        _echo "${ret}"
        _echo ""
    done

}

function _show_grub {

    local grub_path="/boot/grub/grub.cfg"
    if [ ! -f "${grub_path}" ]; then
        grub_path="/mnt/onl/boot/grub/grub.cfg"
        if [ ! -f "${grub_path}" ]; then
            return 0
        fi
    fi

    _banner "Show GRUB Info"

    local grub_info=`cat ${grub_path}`

    _echo "[GRUB Info     ]:"
    _echo "${grub_info}"

}

function _show_driver {
    _banner "Show Kernel Driver"

    local cmd_array=("lsmod | sort" \
               "cat /lib/modules/$(uname -r)/modules.builtin | sort")

    for (( i=0; i<${#cmd_array[@]}; i++ ))
    do
        _echo "[Command]: ${cmd_array[$i]}"
        local ret=$(eval "${cmd_array[$i]} ${LOG_REDIRECT}")
        _echo "${ret}"
        _echo ""
    done
}

function _pre_log {
    _banner "Pre Log"

    _show_i2c_tree_bus
    _show_i2c_tree_bus
    _show_i2c_tree_bus
}

function read_s3ip_sysfs_int {
    local sysfs=$1
    local default_value=$2

    if _check_filepath "${sysfs}"; then
        local reg_value=$(eval "cat ${sysfs}")
        # check if reg_value is integer
        if [[ "$reg_value" =~ ^-?[0-9]+$ ]]; then
            echo $reg_value
        else
            echo $default_value
        fi
    else
        echo $default_value
    fi
}

function read_s3ip_sysfs {
    local sysfs=$1
    local default_value=$2

    if [[ -z "$2" ]]; then
        default_value=""
    fi

    if _check_filepath "${sysfs}"; then
        local reg_value=$(eval "cat ${sysfs}")
            echo $reg_value
    else
        echo $default_value
    fi
}

function _show_board_info {
    _banner "Show Board Info"

    local build_rev_array=(1 2 3 4 5 6 7 8)
    local hw_rev_id_array=(0 1 2 3)
    local hw_rev_array=("Proto" "Alpha" "Beta" "PVT")
    local hw_rev_ga_array=("GA_1" "GA_2" "GA_3" "GA_4")
    local deph_name_array=("NPI" "GA")

    local deph_name=${deph_name_array[${DEPH_ID}]}
    if [ $DEPH_ID -eq 0 ]; then
        HW_REV=${hw_rev_array[${HW_REV_ID}]}
    else
        HW_REV=${hw_rev_ga_array[${HW_REV_ID}]}
    fi

    local build_rev=${build_rev_array[${BUILD_REV_ID}]}

    _echo "[Model Name       ]: ${MODEL_NAME} ($(printf "0x%x" $MODEL_ID))"
    _echo "[Hardware Revision]: ${HW_REV} ($(printf "0x%x" $HW_REV_ID))"
    _echo "[Build Revision   ]: ${build_rev} ($(printf "0x%x" $BUILD_REV_ID))"
    _echo "[Design Phase     ]: ${deph_name} ($(printf "0x%x" $DEPH_ID))"

    # extra board infomation
    if declare -F "_show_extra_info" > /dev/null; then
        _show_extra_info
    fi
}

function _bios_boot_rom_bit {
    if [ -z "$BIOS_BOOT_SEL_REG" ]; then
        return 0
    fi

    local reg=${BIOS_BOOT_SEL_REG%%,*}
    local bit=${BIOS_BOOT_SEL_REG##*,}
    local bios_boot_sel=$(_dd_read_byte $reg)
    bios_boot_sel=$(( (bios_boot_sel & (1 << bit)) >> bit ))
    _echo "[BIOS Boot ROM]: ${bios_boot_sel}"
}

function _bios_boot_rom_mask {
    if [ -z "$BIOS_BOOT_SEL_REG_MASK" ]; then
        return 0
    fi

    local reg=""
    local mask=""
    local offset=""

    IFS=',' read -r \
        reg \
        mask \
        offset \
        <<< "$BIOS_BOOT_SEL_REG_MASK"

    local bios_boot_sel=$(_dd_read_byte $reg)
    bios_boot_sel=$(( (bios_boot_sel & (mask)) >> offset ))
    _echo "[BIOS Boot ROM]: ${bios_boot_sel}"
}

function _bios_version {
    _banner "Show BIOS Version"

    local bios_ver=$(eval "cat /sys/class/dmi/id/bios_version ${LOG_REDIRECT}")
    _echo "[BIOS Version ]: ${bios_ver}"
    _bios_boot_rom_bit
    _bios_boot_rom_mask
}

function _bmc_version {
    _banner "Show BMC Version"

    local bmc_rom1_ver=$(eval "ipmitool raw 0x32 0x8f 0x8 0x1 ${LOG_REDIRECT}")
    local bmc_rom2_ver=$(eval "ipmitool raw 0x32 0x8f 0x8 0x2 ${LOG_REDIRECT}")
    local bmc_active_rom=$(eval "ipmitool raw 0x32 0x8f 0x7 ${LOG_REDIRECT}")

    _echo "[BMC ROM1 Ver  ]: ${bmc_rom1_ver}"
    _echo "[BMC ROM2 Ver  ]: ${bmc_rom2_ver}"
    _echo "[BMC Active ROM]: ${bmc_active_rom}"
}

function _cpld_version_lpc {

    if ! declare -p CPLD_DEV_LPC 2>/dev/null | grep -q 'declare -[aA]' || [ "${#CPLD_DEV_LPC[@]}" -eq 0 ]; then
        return 0
    fi

    _banner "Show CPLD Version (LPC)"

    local cpld_name="" ver_reg="" build_reg=""
    local cpld_ver="" cpld_build="" range=""

    for range in "${CPLD_DEV_LPC[@]}"; do
        IFS=',' read -r cpld_name ver_reg build_reg <<< "$range"

        cpld_ver=$(_dd_read_byte $ver_reg)
        cpld_build=$(_dd_read_byte $build_reg)
        _printf "[${cpld_name} Version]: %d.%02d.%03d\n" $(( (cpld_ver & 2#11000000) >> 6)) $(( cpld_ver & 2#00111111 )) $((cpld_build))
    done
}

function _cpld_version_i2c {
    if [ "${OPT_BYPASS_I2C_COMMAND}" == "${TRUE}" ]; then
        _banner "Show CPLD Version (I2C) (Bypass)"
        return 0
    fi

    if ! declare -p CPLD_I2C_POSITION 2>/dev/null | grep -q 'declare -[aA]' || [ "${#CPLD_I2C_POSITION[@]}" -eq 0 ]; then
        return 0
    fi

    _banner "Show CPLD Version (I2C)"

    local root_bus=""
    local grandparent_addr="" grandparent_chann=""
    local parent_addr="" parent_chann=""
    local dev="" bus="" addr=""
    local range=""

    for range in "${CPLD_I2C_POSITION[@]}"; do
        IFS=',' read -r \
            root_bus \
            grandparent_addr \
            grandparent_chann \
            parent_addr \
            parent_chann \
            dev \
            bus \
            addr \
            <<< "$range"

        if [ -n "${grandparent_addr}" ] && \
            [ -n "${grandparent_chann}" ]; then
            if _check_i2c_device "${root_bus}" "${grandparent_addr}"; then
                i2cset -y -f ${root_bus} ${grandparent_addr} "$(( 1 << grandparent_chann ))"
                grandparent_existed=1
            fi
        fi

        if [ -n "${parent_addr}" ] && \
            [ -n "${parent_chann}" ]; then
            if _check_i2c_device "${root_bus}" "${parent_addr}"; then
                i2cset -y -f ${root_bus} ${parent_addr} "$(( 1 << parent_chann))"
                parent_existed=1
            fi
        fi

        local cpld_ver="" cpld_build=""

        if _check_i2c_device "${root_bus}" "${addr}"; then
            cpld_ver=$(eval "i2cget -y -f ${root_bus} ${addr} 0x2 ${LOG_ERR_REDIRECT}")
            cpld_build=$(eval "i2cget -y -f ${root_bus} ${addr} 0x4 ${LOG_ERR_REDIRECT}")
            cpld_ver=${cpld_ver:-0}
            cpld_build=${cpld_build:-0}
            _printf "[${dev^^} Version]: %d.%02d.%03d\n" $(( (cpld_ver & 2#11000000) >> 6)) $(( cpld_ver & 2#00111111 )) $((cpld_build))
        fi

        if [ "$parent_existed" = "1" ]; then
            i2cset -y -f ${root_bus} ${parent_addr} 0x0
            parent_existed=0
        fi

        if [ "$grandparent_existed" = "1" ]; then
            i2cset -y -f ${root_bus} ${grandparent_addr} 0x0
            grandparent_existed=0
        fi
    done
}

function _cpld_version_sysfs {
    _banner "Show CPLD Version (Sysfs)"

    local num_cplds=0

    # MB CPLD
    num_cplds=$(read_s3ip_sysfs_int "/sys_switch/cpld/number" 0)
    for (( idx=1; idx<=${num_cplds}; idx++ )); do
        local cpld_name=""
        local cpld_ver=""

        cpld_name=$(read_s3ip_sysfs "/sys_switch/cpld/cpld${idx}/description" "CPLD${idx}")
        cpld_ver=$(read_s3ip_sysfs "/sys_switch/cpld/cpld${idx}/firmware_version" "")

        _echo "[${cpld_name} Version]: ${cpld_ver}"
    done

    # MB FPGA
    local num_fpgas=0

    num_fpgas=$(read_s3ip_sysfs_int "/sys_switch/fpga/number" 0)
    for (( idx=1; idx<=${num_fpgas}; idx++ )); do
        local fpga_name=""
        local fpga_ver=""

        fpga_name=$(read_s3ip_sysfs "/sys_switch/fpga/fpga${idx}/description" "FPGA${idx}")
        fpga_ver=$(read_s3ip_sysfs "/sys_switch/fpga/fpga${idx}/firmware_version" "")

        _echo "[${fpga_name} Version]: ${fpga_ver}"
    done
}

function _cpld_version {
    if [ "${BSP_INIT_FLAG}" == "1" ]; then
        _cpld_version_sysfs
    else
        _cpld_version_lpc
        _cpld_version_i2c
    fi
}

function _ucd_version_v1 {
    if ! declare -p UCD_BRD 2>/dev/null | grep -q 'declare -[aA]' || [ "${#UCD_BRD[@]}" -eq 0 ]; then
        return 0
    fi

    _banner "Show UCD Version"

    #get ucd version via BMC
    local ucd_ver_raw=$(eval "ipmitool raw 0x3c 0x8 0x0 ${LOG_ERR_REDIRECT}")
    local ret=$?

    #check return code
    if [ ! $ret -eq 0 ] ; then
        _echo "Require BMC v2.02 or later to get UCD version"
        return $ret
    fi

    #convert hex to ascii
    local ucd_ver_ascii=`echo $ucd_ver_raw | xxd -r -p`

    #get ucd date via BMC
    local ucd_date_raw=$(eval "ipmitool raw 0x3c 0x8 0x1 ${LOG_ERR_REDIRECT}")
    ret=$?

    #check return code
    if [ ! $ret -eq 0 ] ; then
        _echo "Require BMC v2.02 or later to get UCD version"
        return $ret
    fi

    #convert hex to ascii
    local ucd_date_ascii=`echo $ucd_date_raw | xxd -r -p`

    _echo "[${UCD_BRD[i]} UCD REVISION RAW]: ${ucd_ver_raw}"
    _echo "[${UCD_BRD[i]} UCD DATE RAW    ]: ${ucd_date_raw}"
    _echo "[${UCD_BRD[i]} MFR_REVISION    ]: ${ucd_ver_ascii}"
    _echo "[${UCD_BRD[i]} MFR_DATE        ]: ${ucd_date_ascii}"
}

function _ucd_version {
    case "$UVD_SUPPORT_VER" in
        1)
            _ucd_version_v1
            ;;
        *)
            ;;
    esac
    return 0
}

function _show_version {
    _bios_version
    _bmc_version
    _cpld_version
}

function _show_i2c_tree_bus {

    if [ ! -z ${I801_BUS} ]; then
        _banner "Show I2C Tree Bus I801"

        local ret=$(eval "(time i2cdetect -y ${I801_BUS}) ${LOG_REDIRECT}")

        _echo "[I2C Tree ${I801_BUS}]:"
        _echo "${ret}"
    fi

    if [ ! -z ${ISMT_BUS} ]; then
        _banner "Show I2C Tree Bus ISMT"

        local ret=$(eval "(time i2cdetect -y ${ISMT_BUS}) ${LOG_REDIRECT}")

        _echo "[I2C Tree ${ISMT_BUS}]:"
        _echo "${ret}"
    fi

}

function _show_i2c_mux_devices {
    local bus=$1
    local chip_addr=$2
    local channel_num=$3
    local chip_dev_desc=$4
    local is_ch=${5:-false}
    local i=0;
    local startc=0;
    local endc=0;

    if [ -z "${bus}" ] || \
        [ -z "${chip_addr}" ] || \
        [ -z "${channel_num}" ] || \
        [ -z "${chip_dev_desc}" ]; then
        _echo "ERROR: parameter cannot be empty!!!"
        return 1
    fi

    if [ "$is_ch" = "true" ]; then
        startc=${channel_num}
        endc=$(( ${channel_num} + 1 ))
    else
        startc=0
        endc=${channel_num}
    fi

    if _check_i2c_device "$bus" "$chip_addr"; then
        _echo "TCA954X Mux ${chip_dev_desc}"
        _echo "---------------------------------------------------"
        for (( i=startc; i<${endc}; i++ ))
        do
            _echo "TCA954X Mux ${chip_dev_desc} - Channel ${i}"

            # open mux channel
            if ! i2cset -y "$bus" "$chip_addr" "$(( 1 << i ))"; then
                _echo "Error: Failed to switch to channel $i"
                continue
            fi

            # dump i2c tree
            ret=$(eval "(time i2cdetect -y ${bus}) ${LOG_REDIRECT}")
            _echo "${ret}"
            # close mux channel
            i2cset -y ${bus} ${chip_addr} 0x0
            _echo ""
        done
    fi
}

function _show_i2c_tree_bus_mux_i2c {
    if [ "${OPT_BYPASS_I2C_COMMAND}" == "${TRUE}" ]; then
        _banner "Show I2C Tree Bus MUX (I2C) (Bypass)"
        return 0
    fi

    if ! declare -p I2C_TREE 2>/dev/null | grep -q 'declare -[aA]' || [ "${#I2C_TREE[@]}" -eq 0 ]; then
        return 0
    fi

    _banner "Show I2C Tree Bus MUX (I2C)"

    for range in "${I2C_TREE[@]}"; do
        local bus=""
        local grandparent_addr="" grandparent_chann=""
        local parent_addr="" parent_chann=""
        local name channel_num="" addr=""
        local grandparent_existed=0
        local parent_existed=0
        IFS=',' read -r \
            bus \
            grandparent_addr \
            grandparent_chann \
            parent_addr \
            parent_chann \
            name \
            channel_num \
            addr \
            <<< "$range"

        if [ -n "${grandparent_addr}" ] && \
            [ -n "${grandparent_chann}" ]; then
            i2cset -y "${bus}" "${grandparent_addr}" "$(( 1 << grandparent_chann ))"
            grandparent_existed=1
        fi

        if [ -n "${parent_addr}" ] && \
            [ -n "${parent_chann}" ]; then
            i2cset -y "${bus}" "${parent_addr}" "$(( 1 << parent_chann))"
            parent_existed=1
        fi

        _show_i2c_mux_devices "${bus}" "${addr}" "${channel_num}" "${name}"

        if [ "$parent_existed" = "1" ];then
            i2cset -y "${bus}" "${parent_addr}" 0
            parent_existed=0
        fi

        if [ "$grandparent_existed" = "1" ];then
            i2cset -y "${bus}" "${grandparent_addr}" 0
            grandparent_existed=0
        fi
    done
}

function _show_i2c_tree {
    _banner "Show I2C Tree"

    _show_i2c_tree_bus

    if [ "${BSP_INIT_FLAG}" == "1" ]; then
        _echo "TBD"
    else
        _show_i2c_tree_bus_mux_i2c
    fi
}

function _show_i2c_device_info {

    if ! declare -p I2C_DEV_INFO 2>/dev/null | grep -q 'declare -[aA]' || [ "${#I2C_DEV_INFO[@]}" -eq 0 ]; then
        return 0
    fi

    local range=""
    _banner "Show I2C Device Info"
    for range in "${I2C_DEV_INFO[@]}"; do
        local bus=${range%%,*}
        local addr=${range##*,}
        local j=0
        for ((j=0;j<5;j++))
        do
            ret=`i2cget -f -y ${bus} ${addr}`
            _printf "%-20s: %s\n" "[I2C Device ${addr} (${j})]" "$ret"
        done
        sleep 0.4
    done
}

function _show_sys_devices {
    _banner "Show System Devices"

    _echo "[Command]: ls /sys/class/gpio/ ${LS_OPTION}"
    local ret=$(eval "ls /sys/class/gpio/ ${LS_OPTION}")
    _echo "${ret}"

    local file_path="/sys/kernel/debug/gpio"
    if [ -f "${file_path}" ]; then
        _echo ""
        _echo "[Command]: cat ${file_path}"
        _echo "$(cat ${file_path})"
    fi

    _echo ""
    _echo "[Command]: ls /sys/bus/i2c/devices/ ${LS_OPTION}"
    ret=$(eval ls /sys/bus/i2c/devices/ ${LS_OPTION})
    _echo "${ret}"

    _echo ""
    _echo "[Command]: ls /dev/ ${LS_OPTION}"
    ret=$(eval ls /dev/ ${LS_OPTION})
    _echo "${ret}"
}

function _show_sys_eeprom_i2c {
    if ! declare -p SYS_EEPROM &>/dev/null; then
        return 0
    fi

    local bus=""
    local grandparent_addr="" grandparent_chann=""
    local parent_addr="" parent_chann=""
    local addr=""
    local grandparent_existed=0
    local parent_existed=0
    local sys_eeprom=""

    if [ "${OPT_BYPASS_I2C_COMMAND}" == "${TRUE}" ]; then
        _banner "Show System EEPROM (I2C) (Bypass)"
        return 0
    fi

    _banner "Show System EEPROM (I2C)"

    IFS=',' read -r \
        bus \
        grandparent_addr \
        grandparent_chann \
        parent_addr \
        parent_chann \
        addr \
        <<< "$SYS_EEPROM"

    if [ -n "${grandparent_addr}" ] && \
        [ -n "${grandparent_chann}" ]; then
        i2cset -y "${bus}" "${grandparent_addr}" "$(( 1 << grandparent_chann ))"
        grandparent_existed=1
    fi

    if [ -n "${parent_addr}" ] && \
        [ -n "${parent_chann}" ]; then
        i2cset -y "${bus}" "${parent_addr}" "$(( 1 << parent_chann))"
        parent_existed=1
    fi

    local j=0
    # Reset offset to 0 and ensure data integrity.
    for ((j=0;j<10;j++))
    do
        sys_eeprom=$(eval "i2cdump -y ${bus} ${addr} c")
    done

    _echo "[System EEPROM]:"
    _echo "${sys_eeprom}"

    if [ "$parent_existed" = "1" ];then
        i2cset -y "${bus}" "${parent_addr}" 0x0
        parent_existed=0
    fi

    if [ "$grandparent_existed" = "1" ]; then
        i2cset -y -f ${bus} ${grandparent_addr} 0x0
        grandparent_existed=0
    fi
}

function _show_sys_eeprom_sysfs {
    _banner "Show System EEPROM"

    local sys_eeprom=$(eval "cat /sys_switch/syseeprom ${LOG_ERR_REDIRECT} | hexdump -C")
    _echo "[System EEPROM]:"
    _echo "${sys_eeprom}"
}

function _show_sys_eeprom {
    if [ "${BSP_INIT_FLAG}" == "1" ]; then
        _show_sys_eeprom_sysfs
    else
        _show_sys_eeprom_i2c
    fi
}

function _show_gpio_sysfs {

    _banner "Show GPIO Status"

    local max_gpio=`ls /sys/class/gpio/ | grep "gpio[[:digit:]]" | sort -V | tail -n 1`
    local min_gpio=`ls /sys/class/gpio/ | grep "gpio[[:digit:]]" | sort -V | head -n 1`
    local gpio_dir=""
    local gpio_value=""
    local gpio_active=""

    if [ -z $max_gpio ] || [ -z $min_gpio ]  ;then
        _echo "No Contents!!!"
        return 0
    fi

    for (( i=${min_gpio}; i<=${max_gpio}; i++ ))
    do
        if [ ! -d "/sys/class/gpio/gpio${i}" ]; then
            continue
        fi

        if _check_filepath "/sys/class/gpio/gpio${i}/direction"; then
            gpio_dir=$(eval "cat /sys/class/gpio/gpio${i}/direction")
        else
            gpio_dir="N/A"
        fi

        if _check_filepath "/sys/class/gpio/gpio${i}/value"; then
            gpio_value=$(eval "cat /sys/class/gpio/gpio${i}/value")
        else
            gpio_value="N/A"
        fi

        if _check_filepath "/sys/class/gpio/gpio${i}/active_low"; then
            gpio_active=$(eval "cat /sys/class/gpio/gpio${i}/active_low")
        else
            gpio_active="N/A"
        fi

        _echo "[GPIO Pin]: ${i} ,[Direction]: ${gpio_dir} ,[Value]: ${gpio_value} ,[Active Low] : ${gpio_active}"
    done
}

function _show_gpio {

    if [ "${BSP_INIT_FLAG}" == "1" ]; then
        _show_gpio_sysfs
    fi
}

function _show_psu_status_cpld_sysfs {
    _banner "Show PSU Status (CPLD)"
    local num_psu=0
    local desc=""
    local power_ok=0
    local present=0

    num_psu=$(read_s3ip_sysfs_int "/sys_switch/psu/number" 0)
    if [ "${num_psu}" -eq "0" ]; then
        _echo "PSU num is 0!!!"
        return 0
    fi

    for (( i=1; i<=num_psu; i++ )); do
        desc=$(read_s3ip_sysfs "/sys_switch/psu/psu${i}/description" "PSU$((i-1))")
        power_ok=$(read_s3ip_sysfs_int "/sys_switch/psu/psu${i}/out_status" -1)
        present=$(read_s3ip_sysfs_int "/sys_switch/psu/psu${i}/present" -1)
        _echo "[${desc} Power Good Status]: ${power_ok}"
        _echo "[${desc} Present Status   ]: ${present}"
    done
}

function _show_psu_status_cpld {
    if [ "${BSP_INIT_FLAG}" == "1" ]; then
        _show_psu_status_cpld_sysfs
    fi
}

function _show_rov_sysfs {
    case "$ROV_SUPPORT_VER" in
        *)
            ;;
    esac
    return 0
}

function _show_rov {
    if [ "${BSP_INIT_FLAG}" == "1" ]; then
        _show_rov_sysfs
    fi
}

function _eeprom_page_desc {
    local eeprom_page=$1

    if [ "${eeprom_page}" == "0" ]; then
        echo "Lower Page 0 (00h)"
    else
        local hex_page=$(printf "%02X" $((eeprom_page - 1)))
        echo "Upper Page $((eeprom_page - 1)) (${hex_page}h)"
    fi
}

function _eeprom_page_repeat_desc {
    local loop_idx=$1
    local loop_max=$2

    if [ "${loop_max}" == "1" ]; then
        echo ""
    else
        if [ "${loop_idx}" == "0" ]; then
            echo "(1st)"
        elif [ "${loop_idx}" == "1" ]; then
            echo "(2nd)"
        else
            echo "($((loop_idx + 1)))"
        fi
    fi
}

function _eeprom_pages_dump {
    local port=$1
    local type=$2
    local sysfs=$3
    local page_i=0
    local repeate_i=0

    local eeprom_page_array=(0  1  2  3  4  5
                             17 18 19
                             33 34 35 36 37 38 39 40
                             41 42 43 44 45 46 47 48)

    local eeprom_repeat_array=(2 2 2 1 1 1
                               1 1 1
                               1 1 1 1 1 1 1 1
                               1 1 1 1 1 1 1 1)

    if [ "${type}" !=  "QSFP" ] && [ "${type}" !=  "QSFPDD" ] && [ "${type}" !=  "OSFP" ]; then
        # Only support QSFP, QSFPDD, and OSFP
        return 0
    fi

    for (( page_i=0; page_i<${#eeprom_page_array[@]}; page_i++ ))
    do
        for (( repeate_i=0; repeate_i<${eeprom_repeat_array[page_i]}; repeate_i++ ))
        do
            local eeprom_page=$(eval  "dd if=${sysfs} bs=128 count=1 skip=${eeprom_page_array[${page_i}]}  status=none 2>>${LOG_FOLDER_PATH}/eth${port}_eeprom.log | hexdump -C")

            if [ -z "$eeprom_page" ] && [ "${eeprom_repeat_array[page_i]}" == "0" ]; then
                eeprom_page="ERROR!!! The result is empty. It should read failed ${sysfs}!!"
            fi

            echo "[Port${port} EEPROM $(_eeprom_page_desc ${eeprom_page_array[page_i]}) $(_eeprom_page_repeat_desc ${repeate_i} ${eeprom_repeat_array[page_i]})]:" >> ${LOG_FOLDER_PATH}/eth${port}_eeprom.log 2>&1
            echo "${eeprom_page}" >> ${LOG_FOLDER_PATH}/eth${port}_eeprom.log 2>&1
        done
    done
}

function _show_port_status_sysfs {
    _banner "Show Port Status / EEPROM"
    local show_sysfs=${TRUE}
    local num_eths=0
    local eth_attr_names=(
        "description"
        "type"
        "present"
        "low_power_mode"
        "reset"
        "interrupt"
        "tx_fault"
        "rx_los"
        "tx_disable"
        "rate_sel"
        "tx_rate_sel"
        "rx_rate_sel"
    )
    local eth_attr_descs=(
        "Description"
        "Type"
        "Present"
        "Low Power Mode"
        "Reset"
        "Interrupt"
        "TX Fault"
        "RX LOS"
        "TX Disable"
        "Rate Select"
        "TX Rate Select"
        "RX Rate Select"
    )
    local eth_attr_vals=()

    num_eths=$(read_s3ip_sysfs_int "/sys_switch/transceiver/number" 0)
    if [ "${num_eths}" -eq "0" ]; then
        _echo "Transceiver num is 0!!!"
        return 0
    fi

    for (( i=1; i<=num_eths; i++ )); do
        local eth_desc=""
        local eth_present=0
        local num_sysfs=${#eth_attr_names[@]}

        eth_desc=$(read_s3ip_sysfs "/sys_switch/transceiver/eth${i}/${eth_attr_names[0]}")
        # Read and show all eth attributes
        for (( j=0; j<num_sysfs; j++ )); do
            local attr_name=${eth_attr_names[j]}
            local attr_desc=${eth_attr_descs[j]}
            local sysfs_path="/sys_switch/transceiver/eth${i}/${attr_name}"

            if _check_filepath ${sysfs_path} ${FALSE};then
                eth_attr_vals[j]=$(read_s3ip_sysfs "${sysfs_path}" "")
                _echo "[${eth_desc} ${attr_desc}]: ${eth_attr_vals[j]}"

                if [ "${show_sysfs}" == "${TRUE}" ]; then
                    _echo "${sysfs_path}"
                fi
            fi
        done

        # Dump Port EEPROM
        local eeprom_path="/sys_switch/transceiver/eth${i}/eeprom"
        local port_type=${eth_attr_vals[1]}
        local port_present=${eth_attr_vals[2]}

        if [ "${port_present}" == "1" ] && _check_filepath "${eeprom_path}" ${FALSE}; then
            port_eeprom=$(eval "dd if=${eeprom_path} bs=128 count=2 skip=0 status=none ${LOG_ERR_REDIRECT} | hexdump -C")
            if [ "${LOG_FILE_ENABLE}" == "1" ]; then
                if [ "${port_type}" == "SFP" ]; then
                    hexdump -C "${eeprom_path}" > ${LOG_FOLDER_PATH}/eth${i}_eeprom.log 2>&1
                else
                    $(_eeprom_pages_dump ${i} ${port_type} ${eeprom_path})
                fi
            fi
            if [ -z "$port_eeprom" ]; then
                port_eeprom="ERROR!!! The result is empty. It should read failed (${eeprom_path})!!"
            fi
        else
            port_eeprom="N/A"
        fi

        _echo "[Port$((i - 1)) EEPROM Page0-1]:"
        _echo "${port_eeprom}"
        if [ "${show_sysfs}" == "${TRUE}" ]; then
            _echo "${eeprom_path}"
        fi
        _echo ""
    done
}

function _show_port_status {
    if [ "${BSP_INIT_FLAG}" == "1" ]; then
        _show_port_status_sysfs
    fi
}

function _show_eeprom_driver_name {
    if [ "${BSP_INIT_FLAG}" != "1" ]; then
        return
    fi

    _banner "Show EEPROM Driver Name"
    local syseeprom_link=$(readlink /sys_switch/syseeprom)
    if [ -n "$syseeprom_link" ]; then
        local sysfs="${syseeprom_link%/eeprom}"
        local driver_name="NA"
        local full_sysfs="${sysfs}/name"
        [ -f "$full_sysfs" ] && driver_name=$(cat "$full_sysfs")
        _echo "[System EEPROM]: driver($driver_name) path($full_sysfs)"
    else
        _echo "[System EEPROM]: Not found"
    fi

    local num_eths=$(read_s3ip_sysfs_int "/sys_switch/transceiver/number" 0)
    for (( i=1; i<=num_eths; i++ )); do
        local eth_path="/sys_switch/transceiver/eth${i}/eeprom"
        local port_link=$(readlink "$eth_path")
        if [ -n "$port_link" ]; then
            local sysfs="${port_link%/eeprom}"
            local driver_name="NA"
            local full_sysfs="${sysfs}/name"
            [ -f "$full_sysfs" ] && driver_name=$(cat "$full_sysfs")
            _echo "[Port$((i - 1)) EEPROM]: driver($driver_name) path($full_sysfs)"
        else
            _echo "[Port$((i - 1)) EEPROM]: path not linkable"
        fi
    done
}

function _show_driver_build_id {
    local range=""
    local ko_name=""
    local module_name=""
    local driver=""
    local current_build_id=""
    local is_printed="0"
    local gnu_note_head="040000001400000003000000474e5500"

    if [ "${BSP_INIT_FLAG}" != "1" ]; then
        return
    fi


    if ! command -v hexdump >/dev/null 2>&1; then
        return
    fi

    _banner "Show Driver Build ID"

    for range in "${DRIVER_ARRAY[@]}"; do
        IFS=',' read -r \
            ko_name \
            module_name \
            <<< "$range"

        local found_in_loop="0"
        while IFS= read -r driver; do
            [ -z "$driver" ] && continue

            if [ "$found_in_loop" = "0" ]; then
                _echo "[${ko_name}]"
                found_in_loop="1"
                is_printed="1"
            fi

            local driver_build_id=""

            if [[ "$driver" == *.zst ]]; then
                driver_build_id=$(zstd -dcf "$driver" 2>/dev/null | hexdump -ve '1/1 "%.2x"' | grep -o "${gnu_note_head}[0-9a-f]\{40\}" | head -n 1 | cut -c 33- 2>/dev/null)
            else
                driver_build_id=$(hexdump -ve '1/1 "%.2x"' "$driver" | grep -o "${gnu_note_head}[0-9a-f]\{40\}" | head -n 1 | cut -c 33- 2>/dev/null)
            fi
            _printf "%s:\n%s\n" "$driver" "$driver_build_id"
        done < <(find "/lib/modules/$(uname -r)" -type f \( -name "${ko_name}" -o -name "${ko_name}.zst" \) 2>/dev/null)

        if [ "$found_in_loop" = "1" ]; then
            local sys_note="/sys/module/$module_name/notes/.note.gnu.build-id"
            if [ -f "$sys_note" ]; then
                current_build_id=$(hexdump -ve '1/1 "%.2x"' "$sys_note" | cut -c 33-)
                _printf "Current running:\n%s\n" "$current_build_id"
            else
                _echo "Current running: NOT LOADED\n"
            fi
        fi
    done

    if [ "$is_printed" = "0" ]; then
        _echo "No drivers specified in DRIVER_ARRAY were found in the system."
    fi
}

function _show_cpu_info {
    _banner "Show lscpu Info"
    ret=$(lscpu)
    _echo "${ret}"
    _echo ""
}

function _show_cpu_temperature_sysfs {
    local dir_name="" alias_name=""
    local temp_description="" temp_input="" temp_max="" temp_crit=""

    _banner "Show CPU Temperature"
    for dir_name in /sys_switch/temp_sensor/temp*; do
        [ -d "$dir_name" ] || continue

        if [ -f "$dir_name/alias" ]; then
            alias_name=$(cat "$dir_name/alias")
            if echo "$alias_name" | grep -iq "cpu package";then
                temp_description=$(read_s3ip_sysfs "$dir_name/description" "NA")
                temp_input=$(read_s3ip_sysfs_int "$dir_name/value" 0)
                temp_max=$(read_s3ip_sysfs_int "$dir_name/max" 0)
                temp_crit=$(read_s3ip_sysfs_int "$dir_name/max_shutdown_threshold" 0)
                _echo "[CPU Core Temp Description]: ${temp_description}"
                _echo "[CPU Core Temp Input      ]: ${temp_input}"
                _echo "[CPU Core Temp Max        ]: ${temp_max}"
                _echo "[CPU Core Temp Crit       ]: ${temp_crit}"
            fi
        fi
    done
}

function _show_cpu_temperature {
    if [ "${BSP_INIT_FLAG}" == "1" ]; then
        _show_cpu_temperature_sysfs
    fi
}

function _show_cpld_interrupt_sysfs {
    case "$CPLD_INTR_SUPPORT_VER" in
        *)
            ;;
    esac
    return 0
}

function _show_cpld_interrupt {
    if [ "${BSP_INIT_FLAG}" == "1" ]; then
        _show_cpld_interrupt_sysfs
    fi
}

function _show_system_led_sysfs {
    _banner "Show System LED"

    local num=0
    local attr_names=("description" "on_color" "status")
    local attr_descs=("Description" "Color"    "Status")
    local attr_vals=()
    local status_descs=("OFF" "GREEN" "YELLOW" "RED" "BLUE" "GREEN_BLINK" "YELLOW_BLINK" "RED_BLINK" "BLUE_BLINK")

    num=$(read_s3ip_sysfs_int "/sys_switch/sysled/number" 0)
    if [ "${num}" -eq "0" ]; then
        _echo "LED num is 0!!!"
        return 0
    fi

    for (( i=1; i<=num; i++ )); do
        local desc=""
        local num_sysfs=${#attr_names[@]}

        for (( j=0; j<num_sysfs; j++ )); do
            local attr_name=${attr_names[j]}
            local attr_desc=${attr_descs[j]}
            local sysfs_path="/sys_switch/sysled/led${i}/${attr_name}"

            if _check_filepath ${sysfs_path} ${FALSE};then
                attr_vals[j]=$(read_s3ip_sysfs "${sysfs_path}" "")
            fi
        done

        desc=${attr_vals[0]}
        if _check_filepath "/sys_switch/sysled/led${i}/${attr_names[0]}"; then
            _printf "%-35s: %-15s (status=%s)\n" "[${desc}]" "${status_descs[attr_vals[2]]}" "${attr_vals[2]}"
        else
            _printf "%-35s: /sys_switch/sysled/led%s/%s not exist!!!\n" "[${desc}]" "${i}" "${attr_names[0]}"
        fi
    done
}

function _show_system_led {
    if [ "${BSP_INIT_FLAG}" == "1" ]; then
        _show_system_led_sysfs
    fi
}

function _show_beacon_led_sysfs {
    case "$BEACON_LED_SUPPORT_VER" in
        *)
            ;;
    esac
    return 0
}

function _show_beacon_led {
    if [ "${BSP_INIT_FLAG}" == "1" ]; then
        _show_beacon_led_sysfs
    fi
}

function _show_ioport {
    _banner "Show ioport (LPC)"

    local range="" start="" end="" i="" ret="" hex_addr=""
    for range in "${IOPORT_ADDRESS[@]}"; do
        start=${range%%-*}
        end=${range##*-}
        for (( i=$start; i<=$end; i++ )); do
            ret=$(_dd_read_byte ${i})
            _echo "[$(printf "0x%X" "$i")] ${ret}"
        done
    done
}

function _show_cpld_reg_sysfs {

    if ! declare -p CPLD_I2C_POSITION 2>/dev/null | grep -q 'declare -[aA]' || [ "${#CPLD_I2C_POSITION[@]}" -eq 0 ]; then
        return 0
    fi

    _banner "Show CPLD Register"

    local root_bus=""
    local grandparent_addr="" grandparent_chann=""
    local parent_addr="" parent_chann=""
    local dev="" bus="" addr=""
    local range=""
    local reg_dump=""

    for range in "${CPLD_I2C_POSITION[@]}"; do
        IFS=',' read -r \
            root_bus \
            grandparent_addr \
            grandparent_chann \
            parent_addr \
            parent_chann \
            dev \
            bus \
            addr \
            <<< "$range"

        reg_dump=$(eval "i2cdump -f -y $bus $addr ${LOG_REDIRECT}")
        _echo "[$dev Register] (Bus: $bus, Addr: $addr):"
        _echo "${reg_dump}"
    done
}

function _show_cpld_reg {
    if [ "${BSP_INIT_FLAG}" == "1" ] ; then
        _show_cpld_reg_sysfs
    fi
}

function _show_onlpdump {
    _banner "Show onlpdump"

    which onlpdump > /dev/null 2>&1
    local ret_onlpdump=$?
    local timeout_cmd="timeout 20s"

    if [ ${ret_onlpdump} -eq 0 ]; then
        local cmd_array=("${timeout_cmd} onlpdump -d" \
                   "${timeout_cmd} onlpdump -s" \
                   "${timeout_cmd} onlpdump -r" \
                   "${timeout_cmd} onlpdump -e" \
                   "${timeout_cmd} onlpdump -o" \
                   "${timeout_cmd} onlpdump -x" \
                   "${timeout_cmd} onlpdump -i" \
                   "${timeout_cmd} onlpdump -p" \
                   "${timeout_cmd} onlpdump -S")
        for (( i=0; i<${#cmd_array[@]}; i++ ))
        do
            _echo "[Command]: ${cmd_array[$i]}"
            local ret=$(eval "${cmd_array[$i]} ${LOG_REDIRECT} | tr -d '\0'")
            _echo "${ret}"
            _echo ""
        done
    else
        _echo "Not support!"
    fi
}

function _show_onlpd {
    _banner "Show onlpd"

    which onlpd > /dev/null 2>&1
    local ret_onlpd=$?
    local timeout_cmd="timeout 20s"
    local i=0

    if [ ${ret_onlpd} -eq 0 ]; then
        local cmd_array=("${timeout_cmd} onlpd -d" \
                   "${timeout_cmd} onlpd -s" \
                   "${timeout_cmd} onlpd -r" \
                   "${timeout_cmd} onlpd -e" \
                   "${timeout_cmd} onlpd -o" \
                   "${timeout_cmd} onlpd -x" \
                   "${timeout_cmd} onlpd -i" \
                   "${timeout_cmd} onlpd -p" \
                   "${timeout_cmd} onlpd -S")
        for (( i=0; i<${#cmd_array[@]}; i++ ))
        do
            _echo "[Command]: ${cmd_array[$i]}"
            local ret=$(eval "${cmd_array[$i]} ${LOG_REDIRECT} | tr -d '\0'")
            _echo "${ret}"
            _echo ""
        done
    else
        _echo "Not support!"
    fi
}

function _show_onlps {
    _banner "Show onlps"

    which onlps > /dev/null 2>&1
    local ret_onlps=$?
    local timeout_cmd="timeout 20s"
    local i=0

    if [ ${ret_onlps} -eq 0 ]; then
        local cmd_array=("${timeout_cmd} onlps chassis onie show -" \
                   "${timeout_cmd} onlps chassis asset show -" \
                   "${timeout_cmd} onlps chassis env -" \
                   "${timeout_cmd} onlps sfp inventory -" \
                   "${timeout_cmd} onlps sfp bitmaps -" \
                   "${timeout_cmd} onlps chassis debug show -")
        for (( i=0; i<${#cmd_array[@]}; i++ ))
        do
            _echo "[Command]: ${cmd_array[$i]}"
            local ret=$(eval "${cmd_array[$i]} ${LOG_REDIRECT} | tr -d '\0'")
            _echo "${ret}"
            _echo ""
        done
    else
        _echo "Not support!"
    fi
}

function _show_cpld_error_log {
    case "$CPLD_ERR_LOG_SUPPORT_VER" in
        *)
            ;;
    esac
    return 0
}

function _show_memory_correctable_error_count {
    case "$MEM_CORRECTABLE_ERROR_COUNT_SUPPORT_VER" in
        *)
            ;;
    esac
    return 0
}

function _show_usb_info {
    _banner "Show USB Info"
    local i=0
    _echo "[Command]: lsusb -t"
    local ret=$(eval "lsusb -t ${LOG_REDIRECT}")
    _echo "${ret}"
    _echo ""

    _echo "[Command]: lsusb -v"
    ret=$(eval "lsusb -v ${LOG_REDIRECT}")
    _echo "${ret}"
    _echo ""

    _echo ""
    _echo "[Command]: find /sys/devices -name authorized* -exec tail -n +1 {} +"
    ret=$(eval "find /sys/devices -name authorized* -exec tail -n +1 {} + ${LOG_REDIRECT}")
    _echo "${ret}"
    _echo ""

    _echo "[Command]: grep 046b /sys/bus/usb/devices/*/idVendor"
    ret=$(eval "grep 046b /sys/bus/usb/devices/*/idVendor ${LOG_REDIRECT}")
    _echo "${ret}"
    _echo ""

    # check usb auth
    _echo "[USB Port Authentication]: "
    local usb_auth_file_array=("/sys/bus/usb/devices/usb1/authorized" \
                         "/sys/bus/usb/devices/usb1/authorized_default" \
                         "/sys/bus/usb/devices/1-4/authorized" \
                         "/sys/bus/usb/devices/1-4.1/authorized" \
                         "/sys/bus/usb/devices/1-4:1.0/authorized" )

    for (( i=0; i<${#usb_auth_file_array[@]}; i++ ))
    do
        _check_filepath "${usb_auth_file_array[$i]}"
        if [ -f "${usb_auth_file_array[$i]}" ]; then
            ret=$(eval "cat ${usb_auth_file_array[$i]} ${LOG_REDIRECT}")
            _echo "${usb_auth_file_array[$i]}: $ret"
        else
            _echo "${usb_auth_file_array[$i]}: -1"
        fi
    done
}

function _show_scsi_device_info {
    _banner "Show SCSI Device Info"

    local scsi_device_info=$(eval "cat /proc/scsi/sg/device_strs ${LOG_REDIRECT}")
    _echo "[SCSI Device Info]: "
    _echo "${scsi_device_info}"
    _echo ""
}

function _show_onie_upgrade_info {
    _banner "Show ONIE Upgrade Info"

    if [ -d "/sys/firmware/efi" ]; then
        if [ ! -d "/mnt/onie-boot/" ]; then
            mkdir /mnt/onie-boot
        fi

        mount LABEL=ONIE-BOOT /mnt/onie-boot/
        local onie_show_version=`/mnt/onie-boot/onie/tools/bin/onie-version`
        local onie_show_pending=`/mnt/onie-boot/onie/tools/bin/onie-fwpkg show-pending`
        local onie_show_result=`/mnt/onie-boot/onie/tools/bin/onie-fwpkg show-results`
        local onie_show_log=`/mnt/onie-boot/onie/tools/bin/onie-fwpkg show-log`
        umount /mnt/onie-boot/

        _echo "[ONIE Show Version]:"
        _echo "${onie_show_version}"
        _echo ""
        _echo "[ONIE Show Pending]:"
        _echo "${onie_show_pending}"
        _echo ""
        _echo "[ONIE Show Result ]:"
        _echo "${onie_show_result}"
        _echo ""
        _echo "[ONIE Show Log    ]:"
        _echo "${onie_show_log}"
    else
        _echo "BIOS is in Legacy Mode!!!!!"
    fi
}

function _show_disk_info {
    _banner "Show Disk Info"
    local i=0
    local ret=""
    local root_part=$(awk '$2 == "/" {print $1}' /proc/mounts)
    local storage_name=$(lsblk -n -o pkname "$root_part" | head -n 1)
    local storage="/dev/$storage_name"

    local cmd_array=("lsblk"
               "lsblk -O"
               "parted -s -l"
               "fdisk -l $storage"
               "find /sys/fs/ -name errors_count -print -exec cat {} \;"
               "find /sys/fs/ -name first_error_time -print -exec cat {} \; -exec echo '' \;"
               "find /sys/fs/ -name last_error_time -print -exec cat {} \; -exec echo '' \;"
               "df -h")

    for (( i=0; i<${#cmd_array[@]}; i++ ))
    do
        _echo "[Command]: ${cmd_array[$i]}"
        ret=$(eval "${cmd_array[$i]} ${LOG_REDIRECT}")
        _echo "${ret}"
        _echo ""
    done

    # check smartctl command
    ret=`which smartctl`
    if [ ! $? -eq 0 ]; then
        _echo "[command]: smartctl not found (SKIP)!!"
    else
        local cmd=""
        local disk=""
        local smartctl_commands=(
            "smartctl -a"
            "smartctl -x"
        )
        local target_disks=( $(ls /sys/block/$storage_name/slaves/ 2>/dev/null) )
        if [ "${#target_disks[@]}" -eq 0 ]; then
                target_disks=("$storage_name")
        fi

        for cmd in "${smartctl_commands[@]}"; do
            for disk in "${target_disks[@]}"; do
                ret=$(eval "$cmd /dev/$disk ${LOG_REDIRECT}")
                _echo "[command]: $cmd /dev/$disk"
                _echo "${ret}"
                _echo ""
            done
        done
    fi
}

function _show_lspci {
    _banner "Show lspci Info"

    local i=0
    local ret=`lspci`
    _echo "${ret}"
    _echo ""

    _echo "[PCI Bridge Hotplug Status]: "
    local pci_device_id=($(lspci | grep "PLX Technology" | awk '{print $1}'))
    for i in "${pci_device_id[@]}"
    do
        ret=`lspci -vvv -s ${i} | grep HotPlug`
        _echo "${i} ${ret}"
    done
}

function _show_lspci_detail {
    _banner "Show lspci Detail Info"

    local ret=$(eval "lspci -xxxx -vvv ${LOG_REDIRECT}")
    _echo "${ret}"
}

function _show_proc_interrupt {
    _banner "Show Proc Interrupts"
    local i=0
    for i in {1..5};
    do
        ret=$(eval "cat /proc/interrupts ${LOG_REDIRECT}")
        _echo "[Proc Interrupts ($i)]:"
        _echo "${ret}"
        _echo ""
        sleep 1
    done
}

function _show_ipmi_info {
    _banner "Show IPMI Info"

    local i=0
    local ret=""
    local ipmi_folder="/proc/ipmi/0/"

    if [ -d "${ipmi_folder}" ]; then
        local ipmi_file_array=($(ls ${ipmi_folder}))
        for (( i=0; i<${#ipmi_file_array[@]}; i++ ))
        do
            _echo "[Command]: cat ${ipmi_folder}/${ipmi_file_array[$i]} "
            ret=$(eval "cat "${ipmi_folder}/${ipmi_file_array[$i]}" ${LOG_REDIRECT}")
            _echo "${ret}"
            _echo ""
        done
    else
        _echo "Warning, folder not found (${ipmi_folder})!!!"
    fi

    _echo "[Command]: lsmod | grep ipmi "
    ret=`lsmod | grep ipmi`
    _echo "${ret}"
}

function _show_bios_info {
    _banner "Show BIOS Info"

    local i=0
    local cmd_array=("dmidecode -t 0" \
               "dmidecode -t 1" \
               "dmidecode -t 2" \
               "dmidecode -t 3")

    for (( i=0; i<${#cmd_array[@]}; i++ ))
    do
        _echo "[Command]: ${cmd_array[$i]} "
        local ret=$(eval "${cmd_array[$i]} ${LOG_REDIRECT}")
        _echo "${ret}"
        _echo ""
    done
}

function _show_bmc_info {

    if [ "${BMC_SUPPORT}" != "1" ]; then
        return 0
    fi

    _banner "Show BMC Info"

    local i=0
    local cmd_array=("ipmitool mc info" "ipmitool lan print" "ipmitool sel info" \
               "ipmitool fru -v" "ipmitool power status" \
               "ipmitool channel info 0xf" "ipmitool channel info 0x1" \
               "ipmitool sol info 0x1" \
               "ipmitool mc watchdog get" "ipmitool mc info -I usb")

    for (( i=0; i<${#cmd_array[@]}; i++ ))
    do
        _echo "[Command]: ${cmd_array[$i]} "
        local ret=$(eval "${cmd_array[$i]} ${LOG_REDIRECT}")
        _echo "${ret}"
        _echo ""
    done
}

function _show_bmc_device_status {
    case "$BMC_DEV_STAT_SUPPORT_VER" in
        *)
            ;;
    esac
    return 0
}

function _show_bmc_sensors {
    if [ "${BMC_SUPPORT}" != "1" ]; then
        return 0
    fi

    _banner "Show BMC Sensors"

    local ret=$(eval "ipmitool sensor ${LOG_REDIRECT}")
    _echo "[Sensors]:"
    _echo "${ret}"
}


function _show_bmc_sel_raw_data_v1 {
    _banner "Show BMC SEL Raw Data"
    echo "    Show BMC SEL Raw Data, please wait..."

    local ret=""

    if [ "${LOG_FILE_ENABLE}" == "1" ]; then
        _echo "[SEL RAW Data]:"
        ret=$(eval "ipmitool sel save ${LOG_FOLDER_PATH}/sel_raw_data.log > /dev/null ${LOG_REDIRECT}")
        _echo "The file is located at ${LOG_FOLDER_NAME}/sel_raw_data.log"
    else
        _echo "[SEL RAW Data]:"
        ret=$(eval "ipmitool sel save /tmp/log/sel_raw_data.log > /dev/null ${LOG_REDIRECT}")
        cat /tmp/log/sel_raw_data.log
        rm /tmp/log/sel_raw_data.log
    fi
    return 0
}

function _show_bmc_sel_raw_data {
    case "$BMC_SEL_RAW_DATA_SUPPORT_VER" in
        1)
            _show_bmc_sel_raw_data_v1
            ;;
        *)
            ;;
    esac
    return 0
}

function _show_bmc_sel_elist {
    if [ "${BMC_SUPPORT}" != "1" ]; then
        return 0
    fi

    _banner "Show BMC SEL"

    local ret=$(eval "ipmitool sel elist ${LOG_REDIRECT}")
    _echo "[SEL Record]:"
    _echo "${ret}"
}

function _show_bmc_sel_elist_detail {
    if [ "${BMC_SUPPORT}" != "1" ]; then
        return 0
    fi

    _banner "Show BMC SEL Detail -- Abnormal Event"

    _echo "    Show BMC SEL details, please wait..."
    local sel_id_list=""
    local i=0
    local sel_detail=""

    readarray sel_array < <(ipmitool sel elist 2> /dev/null)

    for (( i=0; i<${#sel_array[@]}; i++ ))
    do
        if [[ "${sel_array[$i]}" == *"Undetermined"* ]] ||
           [[ "${sel_array[$i]}" == *"Bus"* ]] ||
           [[ "${sel_array[$i]}" == *"CATERR"* ]] ||
           [[ "${sel_array[$i]}" == *"OEM"* ]] ; then
            _echo  "${sel_array[$i]}"
            local sel_id=($(echo "${sel_array[$i]}" | awk -F" " '{print $1}'))
            sel_id_list="${sel_id_list} 0x${sel_id}"
        fi
    done

    if [ ! -z "${sel_id_list}" ]; then
        sel_detail=$(eval "ipmitool sel get ${sel_id_list} ${LOG_REDIRECT}")
    else
        sel_detail=""
    fi

    _echo "[SEL Record ID]: ${sel_id_list}"
    _echo ""
    _echo "[SEL Detail   ]:"
    _echo "${sel_detail}"
}

function _show_dmesg {
    _banner "Show Dmesg"

    local ret=$(eval "dmesg ${LOG_REDIRECT}")
    _echo "${ret}"
}

function _additional_log_collection {
    _banner "Additional Log Collection"

    local log_file=""
    if [ -z "${LOG_FOLDER_PATH}" ] || [ ! -d "${LOG_FOLDER_PATH}" ]; then
        _echo "LOG_FOLDER_PATH (${LOG_FOLDER_PATH}) not found!!!"
        _echo "do nothing..."
    else
        local log_files_to_copy=("/var/log/kern.log"
                           "/var/log/dmesg"
                           "/var/log/onlpd.log"
                           "/tmp/ipmitool_err_msg")

        for log_file in "${log_files_to_copy[@]}"; do
            if [ -f "$log_file" ]; then
                _echo "copy ${log_file}* to ${LOG_FOLDER_PATH}"
                cp "${log_file}"* "${LOG_FOLDER_PATH}"
            fi
        done
    fi
}

function _show_time {
    _banner "Show Execution Time"
    local end_time=$(date +%s)
    local elapsed_time=$(( end_time - start_time ))

    local ret=`date -d @${start_time}`
    _echo "[Start Time ] ${ret}"

    ret=`date -d @${end_time}`
    _echo "[End Time   ] ${ret}"

    _echo "[Elapse Time] ${elapsed_time} seconds"
}

function _compression {
    _banner "Compression"

    if [ ! -z "${LOG_FOLDER_PATH}" ] && [ -d "${LOG_FOLDER_PATH}" ]; then
        cd "${LOG_FOLDER_ROOT}"
        tar -zcf "${LOG_FOLDER_NAME}".tgz "${LOG_FOLDER_NAME}"

        echo "    The tarball is ready at ${LOG_FOLDER_ROOT}/${LOG_FOLDER_NAME}.tgz"
        _echo "    The tarball is ready at ${LOG_FOLDER_ROOT}/${LOG_FOLDER_NAME}.tgz"
    fi
}

usage() {
    local f=$(basename "$0")
    echo ""
    echo "Usage:"
    echo "    $f [-b] [-d D_DIR] [-h] [-i identifier] [-v]"
    echo "Description:"
    echo "  -b                bypass i2c command (required when NOS vendor use their own platform bsp to control i2c devices)"
    echo "  -d                specify D_DIR as log destination instead of default path /tmp/log"
    echo "  -h                show tech support script usage"
    echo "  -i                insert an identifier in the log file name"
    echo "  -v                show tech support script version"
    echo "Example:"
    echo "    $f -b"
    echo "    $f -d /var/log"
    echo "    $f -h"
    echo "    $f -i identifier"
    echo "    $f -v"
    exit 1
}

function _getopts {
    local OPTSTRING=":bd:fhi:v"
    # default log dir
    local log_folder_root="/tmp/log"
    local identifier=$SN

    while getopts ${OPTSTRING} opt; do
        case ${opt} in
            b)
              OPT_BYPASS_I2C_COMMAND=${TRUE}
              ;;
            d)
              log_folder_root=${OPTARG}
              ;;
            f)
              LOG_FAST=${TRUE}
              ;;
            h)
                usage
                exit 0
                ;;
            i)
              identifier=${OPTARG}
              ;;
            v)
              _show_ts_version
              exit 0
              ;;
            ?)
              echo "Invalid option: -${OPTARG}."
              usage
                exit 1
              ;;
        esac
    done

    LOG_FOLDER_ROOT=${log_folder_root}
    LOG_FOLDER_NAME="log_platform_${identifier}_${DATESTR}"
    LOG_FILE_NAME="log_platform_${identifier}_${DATESTR}.log"
    LOG_FOLDER_PATH="${LOG_FOLDER_ROOT}/${LOG_FOLDER_NAME}"
    LOG_FILE_PATH="${LOG_FOLDER_PATH}/${LOG_FILE_NAME}"
    LOG_REDIRECT="2>&1"
    LOG_ERR_REDIRECT="2>> $LOG_FILE_PATH"
}

function _main {
    echo "The script will take a few minutes, please wait..."
    _check_env
    _pkg_version
    _pre_log
    _show_board_info
    _show_version
    _show_i2c_tree
    _show_i2c_device_info
    _show_sys_devices
    _show_sys_eeprom
    _show_gpio
    _show_psu_status_cpld
    _show_rov
    _show_port_status
    _show_eeprom_driver_name
    _show_driver_build_id
    _show_cpu_info
    _show_cpu_temperature
    _show_cpld_interrupt
    _show_system_led
    _show_beacon_led
    _show_ioport
    _show_cpld_reg
    _show_onlpdump
    _show_onlpd
    _show_onlps
    _show_system_info
    _show_cpld_error_log
    _show_memory_correctable_error_count
    _show_grub
    _show_driver
    _show_usb_info
    _show_scsi_device_info
    _show_onie_upgrade_info
    _show_disk_info
    _show_lspci
    _show_lspci_detail
    _show_proc_interrupt
    _show_bios_info
    _show_bmc_info
    _show_bmc_sensors
    _show_bmc_device_status
    _show_bmc_sel_raw_data
    _show_bmc_sel_elist
    _show_bmc_sel_elist_detail
    _show_dmesg
    _additional_log_collection
    _show_time
}

function _trap_cleanup {
    _compression
    echo "#   The tech-support collection is completed. Please share the tech support log file."
}

#### platform specific
#### platform specific
function _plat_ts_version {
    echo "1.0.0"
}

function _set_plat_vars {
    PLAT="S9620-40DG"

    _set_board_info

    # 2. Dynamic topological routing based on the detected HW_REV_ID
    if [ "${HW_REV_ID}" -le 1 ]; then
        # ===============================================================
        # Alpha / Proto Hardware Configuration (HW_REV_ID <= 1)
        # ===============================================================
        # --- BIOS/BOOT Settings ---
        # EC BIOS BOOT SEL is at LPC offset 0xE30C, bit 6 (D[6])
        # Format: "LPC/I2C Address,Bit Position"
        BIOS_BOOT_SEL_REG="0xE30C,6"
        BIOS_BOOT_SEL_REG_MASK=""

        IOPORT_ADDRESS=(
            "0xE00-0xEFF"   # Main Board CPLD & Registers
            "0x2300-0x23FF" # CPU EC & Other Registers
        )

        CPLD_I2C_POSITION=(
            "${I801_BUS},,,0x76,0,cpld1,2,0x26"
            "${I801_BUS},,,0x76,0,cpld2,2,0x27"
            "${I801_BUS},0x76,3,0x75,0,cpld3,6,0x25"
            "${I801_BUS},0x76,3,0x75,0,cpld4,6,0x24"
        )

        I2C_DEV_INFO=(
            "${I801_BUS},0x76" # PCA9546 Root Mux on I801
            "${ISMT_BUS},0x75" # PCA9546 Root Mux on ISMT
            "2,0x26"           # CPLD1 on Bus 2
            "2,0x27"           # CPLD2 on Bus 2
            "5,0x75"           # Legacy PCA9548 MB Mux on Bus 5
            "6,0x25"           # CPLD3 on Bus 6
            "6,0x24"           # CPLD4 on Bus 6
        )

        I2C_TREE=(
            "${I801_BUS},,,,,9546_ROOT_I801,4,0x76"
            "${ISMT_BUS},,,,,9546_ROOT_ISMT,4,0x75"
            "${I801_BUS},,,0x76,3,9548_MB_MUX,8,0x75"
        )

        SYS_EEPROM="${ISMT_BUS},,,,,0x57"
        BMC_SUPPORT=1

    else
        # ===============================================================
        # Beta Hardware Configuration (HW_REV_ID > 1)
        # ===============================================================
        # --- BIOS/BOOT Settings ---
        # EC BIOS BOOT SEL is at LPC offset 0xE30C, bit 6 (D[6])
        # Format: "LPC/I2C Address,Bit Position"
        BIOS_BOOT_SEL_REG="0xE30C,6"
        BIOS_BOOT_SEL_REG_MASK=""

        # --- LPC I/O Port Scan Range ---
        # Define the LPC address ranges to be dumped via dd command
        IOPORT_ADDRESS=(
            "0xE00-0xEFF"   # Main Board CPLD & Registers
            "0x2300-0x23FF" # CPU EC & Other Registers
        )

        # --- I2C Topology & Device Definition (Beta: CPLD Mux Design) ---
        # Define the CPLD positions within the I2C tree for direct i2cget commands.
        # Format: root_bus, grandparent_addr, grandparent_channel, parent_addr, parent_channel, device_name, target_bus, target_addr
        CPLD_I2C_POSITION=(
            "${I801_BUS},,,0x76,0,cpld1,2,0x26"
            "${I801_BUS},,,0x76,0,cpld2,2,0x27"
            "${I801_BUS},,,0x76,3,cpld3,5,0x25"
            "${I801_BUS},,,0x76,3,cpld4,5,0x24"
        )

        # Define simple I2C devices to be polled/dumped directly
        # Format: "bus,address"
        I2C_DEV_INFO=(
            "${I801_BUS},0x76" # PCA9546 Root Mux on I801
            "${ISMT_BUS},0x75" # PCA9546 Root Mux on ISMT
            "2,0x26"           # CPLD1 on Bus 2
            "2,0x27"           # CPLD2 on Bus 2
            "5,0x25"           # CPLD3 on Bus 5
            "5,0x24"           # CPLD4 on Bus 5
        )

        # Define the full I2C Tree topology for MUX traversal
        # Format: bus, grandparent_addr, grandparent_channel, parent_addr, parent_channel, name, channel_num, addr
        I2C_TREE=(
            "${I801_BUS},,,,,9546_ROOT_I801,4,0x76"
            "${ISMT_BUS},,,,,9546_ROOT_ISMT,4,0x75"
            "${ISMT_BUS},,,0x75,1,9546_MB_MUX,4,0x76"
        )

        # Define System EEPROM path
        SYS_EEPROM="${ISMT_BUS},,,,,0x57"

        # --- Feature Support Flags ---
        # 1: Supported, 0: Not Supported
        BMC_SUPPORT=1
    fi
}

function _show_extra_info {
    :
}

function _set_board_info {
    # Default arrays mapping the hardware ID to actual model strings
    local model_id_array=($((2#11101110)) $((2#11101111)))
    local model_name_array=("Q3A S9620-40DG ALPHA" "Q3A S9620-40DG BETA")
    local ret=""
    local found="0"
    local i=0

    # Read SKU ID from CPLD1 0xE00 Register via LPC
    local model_id=$(_dd_read_byte 0xE00)
    ret=$?

    if [ $ret -eq 0 ]; then
        # Ensure proper extraction and cast to integer
        model_id=$((model_id))
        MODEL_ID=$(((model_id & 2#11111111) >> 0))

        for (( i=0; i<${#model_id_array[@]}; i++ ))
        do
            if (( MODEL_ID == model_id_array[i] )); then
                MODEL_NAME="${model_name_array[$i]}"
                found="1"
                break
            fi
        done

        if [ "$found" = "0" ]; then
            MODEL_NAME="S9620-40DG UNKNOWN"
        fi
    fi

    # Read CPLD1 0x01 HW & Build Revision Register via LPC
    local board_rev_id=$(_dd_read_byte 0xE01)
    ret=$?

    if [ $ret -eq 0 ]; then
        board_rev_id=$((board_rev_id))

        # Design Phase: DEPH D[2]
        DEPH_ID=$(((board_rev_id & 2#00000100) >> 2))

        # Hardware Revision: HW Rev D[0:1]
        HW_REV_ID=$(((board_rev_id & 2#00000011) >> 0))

        # Build Revision: Build Rev D[3:5]
        BUILD_REV_ID=$(((board_rev_id & 2#00111000) >> 3))
    fi
}

####

_getopts $@
trap '_trap_cleanup' EXIT ERR
_main
